# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_hit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='last_hit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
