# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20161126_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='context_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='text_english',
            field=models.TextField(null=True),
        ),
    ]
