# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:20
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line_height', models.PositiveIntegerField(default=20)),
                ('char_color', models.CharField(default='000000', max_length=7)),
                ('font', models.FileField(blank=True, null=True, upload_to=settings.STATIC_ROOT + '/uploads/')),
                ('font_size', models.PositiveIntegerField(default=16)),
                ('padding_x', models.IntegerField(default=0)),
                ('padding_y', models.IntegerField(default=0)),
                ('image', models.FileField(blank=True, null=True, upload_to=settings.STATIC_ROOT + '/uploads/')),
            ],
        ),
    ]
