# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0003_auto_20161126_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile', to='quote.Quote'),
        ),
    ]
