# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0005_template_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='english',
            field=models.BooleanField(default=False),
        ),
    ]
